language: ruby
services:
  - mongodb
rvm:
  - 2.1.0
before_script:
  - mongo lingrbot-github-to-lingr-test --eval 'db.addUser("test", "test");'
bundler_args:
script:
  - export MONGODB_URL=mongodb://test:test@localhost:27017/lingrbot-github-to-lingr-test
  - bundle install
  - bundle exec rake spec
gemfile:
  - Gemfile
